# Generated by Django 5.2 on 2026-09-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A friendly label for this connection', max_length=255)),
                ('host', models.CharField(help_text='Database server hostname or IP address', max_length=255)),
                ('port', models.IntegerField(default=5432, help_text='Database server port')),
                ('dbname', models.CharField(help_text='Name of the PostgreSQL database', max_length=255, verbose_name='Database Name')),
                ('username', models.CharField(help_text='Database username', max_length=255)),
                ('password', models.CharField(help_text='Database password', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Database Connection',
                'verbose_name_plural': 'Database Connections',
                'ordering': ['-created_at'],
            },
        ),
    ]
