# Generated by Django 5.2 on 2026-09-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='last_vacuum',
            field=models.DateTimeField(blank=True, default=None, help_text='Timestamp of the last vacuum operation', null=True, verbose_name='Last Vacuum'),
        ),
    ]
