# Generated by Django 5.2 on 2026-09-04 08:18

import connections.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_databaseconnection_last_vacuum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='password',
            field=connections.models.EncryptedCharField(blank=True, help_text='Database password (stored encrypted)', max_length=255),
        ),
    ]
