# Generated by Django 5.2 on 2026-09-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_alter_databaseconnection_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='ssl_mode',
            field=models.CharField(choices=[('require', 'Required'), ('prefer', 'Preferred'), ('disable', 'Disabled')], default='prefer', help_text='SSL connection mode', max_length=10),
        ),
    ]
