# Generated by Django 5.2 on 2026-09-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_databaseconnection_ssl_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last update to this connection', verbose_name='Last Updated'),
        ),
    ]
