# Generated by Django 5.2 on 2026-09-04 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0003_alter_databaseconnection_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacuumHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(max_length=255)),
                ('is_success', models.CharField(choices=[('success', 'Success'), ('partial_success', 'Partial Success'), ('fail', 'Fail')], max_length=20)),
                ('vacuum_date', models.DateTimeField(auto_now_add=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacuum_histories', to='connections.databaseconnection')),
            ],
            options={
                'verbose_name_plural': 'Vacuum Histories',
                'ordering': ['-vacuum_date'],
            },
        ),
    ]
